# Generated by Django 5.0 on 2023-12-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='county',
            new_name='country',
        ),
    ]
